### ISSUE TITLE
Database initialisation is not idempotent

### ISSUE THREAD

**Issue by cameronkerrnz** [bertvv/ansible-role-mariadb#2]
Using mariadb_init_scripts will call the SQL every time; thereby re-initialising the database (as per the SQL) every time.

This is not the expected thing, and the documentation should clearly highlight this behaviour. I would have expected the script to only execute if the database was missing.

I think a 'when' clause is needed in the following:

```
- name: Initialise databases
  mysql_db:
    name: "{{ item.database }}"
    state: import
    target: "/tmp/{{ item.script|basename }}"
  with_items: "{{ mariadb_init_scripts }}"
  tags: mariadb
```

(RHEL7.3 mariadb from package; Ansible 2.2.1.0)
